# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ControlsCanvas < Formula
  desc "A terminal-based UI tool for interactively selecting and managing cloud security controls"
  homepage "https://github.com/revanite-io/controls-canvas"
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/revanite-io/controls-canvas/releases/download/v0.0.4/controls-canvas_Darwin_x86_64.tar.gz"
      sha256 "706998f1980972d7caaac0c3d2d1b7abd32c685048566855fa22083814c60726"

      def install
        bin.install "controls-canvas"
      end
    end
    on_arm do
      url "https://github.com/revanite-io/controls-canvas/releases/download/v0.0.4/controls-canvas_Darwin_arm64.tar.gz"
      sha256 "73cbd729af482c1076416d0790043191bbeefdb634f31edc4e2d395865156898"

      def install
        bin.install "controls-canvas"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/revanite-io/controls-canvas/releases/download/v0.0.4/controls-canvas_Linux_x86_64.tar.gz"
        sha256 "2636ed97df695d409c8bc4757bbbeb626e01b64bd8342dfaa4e75bf6df65273e"

        def install
          bin.install "controls-canvas"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/revanite-io/controls-canvas/releases/download/v0.0.4/controls-canvas_Linux_arm64.tar.gz"
        sha256 "69b0cc15429880f4e1adb7bf9d080797faed23d16d4591bfe7ecb6c5d928316e"

        def install
          bin.install "controls-canvas"
        end
      end
    end
  end
end
