# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ControlsCanvas < Formula
  desc "A terminal-based UI tool for interactively selecting and managing cloud security controls"
  homepage "https://github.com/revanite-io/controls-canvas"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/revanite-io/controls-canvas/releases/download/v0.0.3/controls-canvas_Darwin_x86_64.tar.gz"
      sha256 "cce14a287628bdaff0c4fb8a3c71c0b16d20307d4f22036f339742b000a9240f"

      def install
        bin.install "controls-canvas"
      end
    end
    on_arm do
      url "https://github.com/revanite-io/controls-canvas/releases/download/v0.0.3/controls-canvas_Darwin_arm64.tar.gz"
      sha256 "5fd0c10740f56ff8498a9f93ab47d23ca89388161479f6aad966c025a7560e33"

      def install
        bin.install "controls-canvas"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/revanite-io/controls-canvas/releases/download/v0.0.3/controls-canvas_Linux_x86_64.tar.gz"
        sha256 "8762f344497bf44aceef5f8382e50a6aaa3b7d82923e6b4d6e43b24011bb3947"

        def install
          bin.install "controls-canvas"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/revanite-io/controls-canvas/releases/download/v0.0.3/controls-canvas_Linux_arm64.tar.gz"
        sha256 "f03a31a33c4d3a68ec75ef9f9bc6d33b9b8d94aa9f7324a8e50cf2ac8af0d4ce"

        def install
          bin.install "controls-canvas"
        end
      end
    end
  end
end
